// <auto-generated />
using CafeteriaWebApi.DataEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CafeteriaWebApi.Migrations
{
    [DbContext(typeof(CafeteriaContext))]
    [Migration("20180201093650_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CafeteriaWebApi.Models.Booking", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BookingDate");

                    b.Property<string>("ContactNumber");

                    b.Property<string>("CustomerName");

                    b.Property<string>("Email");

                    b.Property<string>("Message");

                    b.Property<string>("ReferenceId");

                    b.Property<int?>("StatusId");

                    b.Property<int>("TotalPersons");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("CafeteriaWebApi.Models.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("StatusDate");

                    b.Property<string>("StatusDescription");

                    b.Property<int>("StatusId");

                    b.Property<string>("StatusName");

                    b.HasKey("Id");

                    b.ToTable("BookingStatus");
                });

            modelBuilder.Entity("CafeteriaWebApi.Models.Booking", b =>
                {
                    b.HasOne("CafeteriaWebApi.Models.BookingStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
